.github: add initial workflow to run tests
crashappsec/libcon4m pull request #38
Opened 2024-06-18 18:25 UTC by ee7

Add an initial workflow to run `dev run` in CI on the Linux and macOS runners. The output currently needs to be inspected manually, but this PR gives us a base to build on and could already help catch regressions like #37 (and make it easier to verify fixes on other platforms).

Note that currently:

- The `dev run` command exiting with an exit status of 0 does not imply that the tests pass.
- The workflow indicates success even when `dev run` segfaults.

We can improve such things over time.
 
Also use the latest stable GCC release (GCC 14.1) in the Linux job to help make newer compiler warnings more visible.

Closes: #34 (we can make follow-up tickets for e.g. the exit status)
Refs: #35
Refs: #37

---

To-do:

- [x] Fix error on macOS: `meson.build:170:14: ERROR: C shared or static library 'crypto' not found`
- [x] Resolve any conflict with `main` after we merge a PR that fixes #37

2024-06-20 17:31 UTC, miki725 requested changes

2024-06-20 17:31 UTC, miki725 commented on .github/workflows/test.yml
> +              exit 1
lets use github expressions for this:

```
- name: install deps (linus)
  if: runner.os == 'Linux'
  run: sudo apt install meson ninja build

- name: install deps (mac)
  if: runner.os == 'macOS'
  ...
```

2024-06-21 11:41 UTC, miki725 commented on .github/workflows/test.yml
> +              exit 1
When split it just shows up better in GitHub logs. The command you actually care about is directly displayed vs being collapsed

2024-06-21 11:42 UTC, miki725 approved these changes

2024-06-21 13:40 UTC, viega reviewed
It doesn't seem to deal w/ the exit code / crashes.  For instance, it's certainly not working on Linux right now based on the runner output, but it still passes. 

Also, since I'm generally not working on a Linux box and switching is a bit of a PITA, would appreciate some insight there.

2024-06-21 13:52 UTC, miki725 commented
https://github.com/crashappsec/libcon4m/blob/833300442d95e6ca7b49104417873c0c671caa00/dev#L128-L139

looks like exit code is not honored in the `dev` script in general. not sure how that works on mac at all. we can either `set -e` in the script to bail out on any non-successful commands or explicitly handle the case when `./c4test` fails

2024-06-21 14:48 UTC, viega commented
I don't understand the need to be rushing it in if it isn't where it needs to be. There's no need to overengineer the build; I don't want to do more than the bare minimum necessary (for instance with the dev script), because they're not a priority yet. Breaking this up feels like an invitation to bikeshed, and I would rather stay focused.

2024-06-27 12:14 UTC, merged